version: '3'
services:

  front.public:
    build:
      dockerfile: Dockerfile
      context: front/public
    container_name: front.public
    volumes:
      - ./front/public/src:/usr/src/app
    ports:
      - '5173:5173'
    env_file:
      - ./.env
    networks:
      - sne
    depends_on:
      - laravel.api

  laravel.api:
    build:
      dockerfile: Dockerfile_api
      context: back/api
    container_name: laravel.api
    volumes:
      - ./back/api/src:/var/www/html
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    networks:
      - sne
    depends_on:
      - db.mysql

  db.mysql:
    build:
      dockerfile: ./services/mysql/Dockerfile
      context: .
    container_name: db.mysql
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - sne

  nginx.router:
    build:
      dockerfile: ./services/nginx/Dockerfile
      context: .
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - sne
    depends_on:
      - laravel.api
      - db.mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db.mysql.main
      - PMA_PORT=3306
    networks:
      - sne


networks:
  sne:
    driver: bridge
