version: '3'
services:

  front.public:
    build:
      dockerfile: Dockerfile
      context: front/public
    container_name: front.public
    volumes:
      - ./front/public/src:/usr/src/app
    ports:
      - '5173:5173'
    networks:
      - sne
    depends_on:
      - laravel.api

  laravel.api:
    build:
      dockerfile: Dockerfile_api
      context: back/api
    container_name: laravel.api
    volumes:
      - ./back/api/src:/var/www/html
    ports:
      - '8000:8000'
    networks:
      - sne

  nginx.router:
    build:
      dockerfile: ./services/nginx/Dockerfile
      context: .
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - sne
    depends_on:
      - laravel.api

networks:
  sne:
    driver: bridge
